repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.4
      hooks:
          - id: aoc-tiles
            args:
                - --contrast-improvement-type=dark
                - --count-as-solved-when=on_leaderboard
